### PR TITLE
Deploy Sentry on Heroku with uwsgi + Nginx

### PR DESCRIPTION
**Pull request by mrluanma**

### CODE REVIEW

**Comment by dahlia** [comment]
What improvements are there for using uWSGI + Nginx over Gunicorn on Heroku?  It’s not a refusing expression, but I’m just curious.

**Comment by mrluanma** [comment]
IMHO, Serving assets with Nginx is a big win, and uwsgi is at least as performant as Gunicorn and easy to setup too.

**Comment by dahlia** [comment]
Is it a common practice to build Nginx using buildpack to efficiently serve static assets on Heroku?

**Comment by mrluanma** [comment]
No, not at all.  Heroku is not for static assets, but for small deployment, it doesn't matter.

**Comment by dahlia** [comment]
Thanks for your effort.

**Pull request merged**
